extra_fn_clean_exts:
    - type: regex
      pattern: '_\w*_S\d+_L\d{3}_R\d_\d{3}'
    - '.LibraryComplexity'

top_modules:
- 'fastqc'

table_columns_visible:
    FastQC:
        percent_duplicates: False
        percent_gc: True
        avg_sequence_length: True
        percent_fails: True
        total_sequences: True
